# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2025

WORKDIR C:\TEMP
ENV TEMP=C:\TEMP
ENV TMP=C:\TEMP
ENV JAVA_HOME=C:\OpenJDK
ENV ANT_HOME=C:\apache-ant-1.10.15
ENV _NT_SYMBOL_PATH=cache*C:\Symbols;srv*https://msdl.microsoft.com/download/symbols
RUN SETX /M PATH "%PATH%;C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\IDE;C:\ABSuite\ABSF\trunk\Debug\bin64;C:\Program Files\WinZip;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64;C:\OpenJDK\bin;C:\Program Files (x86)\node-v24.12.0-win-x64;C:\apache-ant-1.10.15\bin;"

COPY Deploy/ C:\Deploy\

RUN PowerShell -File C:\Deploy\Script\ABSuite.Dev.ps1 -DeployFolder "C:\Deploy"

CMD ["cmd.exe", "/K", "C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\VsDevCmd.bat"]