# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2025

WORKDIR C:\TEMP
ENV TEMP=C:\TEMP
ENV TMP=C:\TEMP

# Install Visual Studio Build Tools 2022
COPY Software/ C:\Software\
RUN PowerShell -File C:\Software\VS2022_BuildTools.install.ps1 C:\Software\VS2022.vsconfig

CMD ["cmd.exe", "/K", "%ProgramFiles%\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\VsDevCmd.bat"]